-- LESSON 7

--TASK 1
SELECT 
    LOCATION_ID,
    STREET_ADDRESS,
    CITY,
    locations.state_province,
    COUNTRY_NAME
FROM LOCATIONS NATURAL JOIN COUNTRIES;

--TASK 2

SELECT+
    LAST_NAME,
    DEPARTMENT_ID,
    DEPARTMENT_NAME
FROM EMPLOYEES NATURAL JOIN DEPARTMENTS;

-- TASK 3
SELECT 
    LAST_NAME,
    JOB_ID,
    EMPLOYEES.DEPARTMENT_ID,
    DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID  = LOCATIONS.LOCATION_ID
WHERE LOCATIONS.CITY LIKE 'Toronto';

-- TASK 4

SELECT 
    E.LAST_NAME "Employee",
    E.EMPLOYEE_ID "EMP#", 
    M.LAST_NAME "Manager",
    M.EMPLOYEE_ID "MGR#"
FROM EMPLOYEES E JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID;

-- TASK 5
SELECT 
    E.LAST_NAME "Employee",
    E.EMPLOYEE_ID "EMP#", 
    M.LAST_NAME "Manager",
    M.EMPLOYEE_ID "MGR#"
FROM EMPLOYEES E LEFT JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID;

-- TASK 6
SELECT 
    E.DEPARTMENT_ID "DEPARTAMENT",
    E.LAST_NAME "PRACUŚ",
    C.LAST_NAME "KOLEGA"
FROM EMPLOYEES E JOIN EMPLOYEES C
ON E.DEPARTMENT_ID = C.DEPARTMENT_ID
WHERE E.LAST_NAME NOT LIKE C.LAST_NAME;

--TASK 7 
SELECT * FROM JOB_GRADES;
SELECT * FROM JOBS;

SELECT 
    E.LAST_NAME,
    E.JOB_ID,
    DEPARTMENTS.DEPARTMENT_NAME,
    E.SALARY,
    G.GRADE_LEVEL
FROM EMPLOYEES E
NATURAL JOIN DEPARTMENTS
JOIN JOB_GRADES G
ON E.SALARY > G.LOWEST_SAL AND E.SALARY < G.HIGHEST_SAL;

--Task 8

SELECT
    LAST_NAME,
    HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE > (SELECT HIRE_DATE FROM EMPLOYEES WHERE LAST_NAME LIKE 'Davies');

--
SELECT 
    e1.LAST_NAME,
    e1.HIRE_DATE
FROM 
    EMPLOYEES e1
JOIN 
    EMPLOYEES e2
    ON e1.HIRE_DATE > e2.HIRE_DATE
WHERE 
    e2.LAST_NAME = 'Davies';


