--LESSON 10

--TASK 1
CREATE TABLE MY_EMPLOYEE(
    ID NUMBER(4) NOT NULL ,
    LAST_NAME VARCHAR2(25),
    FIRST_NAME VARCHAR2(25),
    USERID VARCHAR2(8),
    SALARY NUMBER(9,2)
    );
    
--TASK 2
DESCRIBE MY_EMPLOYEE;

--TASK 3
INSERT INTO MY_EMPLOYEE VALUES (1, 'Patel', 'Ralph', 'rpatel', 895);


--TASK 4
INSERT INTO MY_EMPLOYEE(ID, LAST_NAME, FIRST_NAME, USERID, SALARY) VALUES (2, 'Dancs', 'Betty', 'bdancs', 860);


--TASK 5
SELECT * FROM MY_EMPLOYEE;


--TASK 6 & 7
INSERT INTO MY_EMPLOYEE(ID, LAST_NAME, FIRST_NAME, USERID, SALARY) VALUES (&ID, '&LAST_NAME', '&FIRST_NAME', '&USERID', &SALARY);


--TASK 8
SELECT * FROM MY_EMPLOYEE;


--TASK 9
COMMIT;



--TASK 10
UPDATE MY_EMPLOYEE
SET LAST_NAME = 'Drexler'
WHERE ID = 3;

COMMIT;


--TASK 11
UPDATE MY_EMPLOYEE
SET SALARY = 1000
WHERE SALARY < 900;

COMMIT;


--TASK 12
SELECT * FROM MY_EMPLOYEE;


-- TASK 13
DELETE MY_EMPLOYEE
WHERE LAST_NAME = 'Dancs' AND FIRST_NAME = 'Betty';


--TASK 14
SELECT * FROM MY_EMPLOYEE;


--TASK 15
COMMIT;