-- LESSON 9


-- TASK 1
SELECT 
    department_id
FROM employees
MINUS
SELECT 
    department_id
FROM employees
WHERE job_id = 'ST_CLERK'
ORDER BY department_id;


--TASK 2
SELECT
    COUNTRY_ID,
    COUNTRY_NAME
FROM COUNTRIES
MINUS
SELECT
    C.COUNTRY_ID,
    C.COUNTRY_NAME
FROM COUNTRIES C 
    JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
    JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID;
  
    
-- TASK 3
SELECT 
    JOB_ID,
    DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10
UNION ALL
SELECT 
    JOB_ID,
    DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50
UNION ALL
SELECT 
    JOB_ID,
    DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20;


--TASK 4
DESCRIBE JOB_HISTORY;

SELECT
    E.EMPLOYEE_ID,
    E.JOB_ID
FROM EMPLOYEES E
WHERE E.JOB_ID = (
    SELECT JH.JOB_ID
    FROM JOB_HISTORY JH
    WHERE JH.EMPLOYEE_ID = E.EMPLOYEE_ID
    ORDER BY JH.START_DATE
    FETCH FIRST 1 ROW ONLY
);

--TASK 5
SELECT
    NULL AS LAST_NAME,
    DEPARTMENT_ID,
    DEPARTMENT_NAME
FROM DEPARTMENTS
UNION ALL
SELECT
    LAST_NAME,
    DEPARTMENT_ID,
    NULL
FROM EMPLOYEES
ORDER BY LAST_NAME;