-- LESSON 13

-- TASK 1
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    phone_number,
    hire_date,
    salary
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) > 1997;


--TASK 2
SELECT 
    LAST_NAME,
    JOB_ID,
    SALARY,
    COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY SALARY DESC;

-- TASK 3
SELECT
    'The salary of ' 
    || LAST_NAME 
    || ' after 10% raise is '
    || TO_CHAR(salary * 1.1) 
    "New Salary"
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;


--TASK 4
SELECT
    LAST_NAME,
    EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM HIRE_DATE) "Years",
    EXTRACT(MONTH FROM SYSDATE) - EXTRACT(MONTH FROM HIRE_DATE) "MONTHS"
FROM EMPLOYEES;


--TASK 5
SELECT 
    LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'J%' 
OR LAST_NAME LIKE 'K%' 
OR LAST_NAME LIKE 'L%' 
OR LAST_NAME LIKE 'M%';


--TASK 6
SELECT
    LAST_NAME,
    SALARY,
    NVL2(COMMISSION_PCT,'YES', 'NO') "COMMISSION"
FROM EMPLOYEES;


--TASK 7
SELECT
    D.DEPARTMENT_NAME,
    D.LOCATION_ID,
    E.LAST_NAME,
    E.JOB_ID,
    E.SALARY
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.LOCATION_ID = &LOCATION;

--TASK 8
SELECT
    COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%n';


--TASK 9
SELECT
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    D.LOCATION_ID,
    COUNT(E.EMPLOYEE_ID)
FROM DEPARTMENTS D JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME, D.LOCATION_ID;


--TASK 10
SELECT
    DISTINCT JOB_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10
OR DEPARTMENT_ID = 20;


--TASK 11
SELECT
    JOB_ID,
    COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10
OR DEPARTMENT_ID = 90
GROUP BY JOB_ID;


--TASK 12
SELECT
    LAST_NAME,
    HIRE_DATE
FROM EMPLOYEES
WHERE EXTRACT(DAY FROM HIRE_DATE) < 16;


--TASK 13
SELECT
    LAST_NAME,
    SALARY,
    SALARY / 1000 "THOUSANDS"
FROM EMPLOYEES;


--TASK 14
DESCRIBE JOB_GRADES;

SELECT 
    E.LAST_NAME,
    M.LAST_NAME,
    M.SALARY,
    JG.GRADE_LEVEL
FROM EMPLOYEES E JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID
JOIN JOB_GRADES JG
ON M.SALARY > JG.LOWEST_SAL AND M.SALARY < JG.HIGHEST_SAL
WHERE M.SALARY > 15000;


--TASK 15
SELECT
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(A.EMPLOYEE_ID),
    AVG(A.SALARY),
    E.LAST_NAME,
    E.SALARY,
    E.JOB_ID
FROM DEPARTMENTS D JOIN EMPLOYEES A
ON D.DEPARTMENT_ID = A.DEPARTMENT_ID
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.LAST_NAME, E.SALARY, E.JOB_ID
ORDER BY DEPARTMENT_ID;



