-- LESSON 6

--TASK 4
SELECT
    MIN(SALARY),
    MAX(SALARY),
    AVG(SALARY)
FROM EMPLOYEES;

--TASK 5
SELECT
    MIN(SALARY),
    MAX(SALARY),
    TRUNC(AVG(SALARY))
FROM EMPLOYEES
GROUP BY JOB_ID;

-- TASK 6
SELECT 
    JOB_ID,
    COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY JOB_ID;

-- TASK 7
SELECT 
    COUNT(DISTINCT MANAGER_ID)
FROM EMPLOYEES;

--TASK 8
SELECT 
    MAX(SALARY) - MIN(SALARY)
FROM EMPLOYEES;

-- TASK 9
SELECT 
    MANAGER_ID,
    MIN(SALARY)
FROM EMPLOYEES JOIN JOBS
ON EMPLOYEES.JOB_ID = JOBS.JOB_ID
WHERE MANAGER_ID IS NOT NULL
AND JOBS.MIN_SALARY > 6000
GROUP BY MANAGER_ID
ORDER BY MIN(SALARY) DESC;


--TASK 10
SELECT
    COUNT(*) AS Total_Employees,
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 1994 THEN 1 END) AS Hired_1994,
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2005 THEN 1 END) AS Hired_2005,
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2006 THEN 1 END) AS Hired_2006,
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2007 THEN 1 END) AS Hired_2007,
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2008 THEN 1 END) AS Hired_2008,
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2009 THEN 1 END) AS Hired_2009,
    COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2010 THEN 1 END) AS Hired_2010
FROM EMPLOYEES;


