-- LESSON 8

select * from employees;

-- TASK 1
SELECT 
    C.LAST_NAME "KOLEGA",
    C.HIRE_DATE
FROM EMPLOYEES E JOIN EMPLOYEES C
ON E.DEPARTMENT_ID = C.DEPARTMENT_ID
WHERE E.LAST_NAME LIKE '%&NAME%'
AND C.LAST_NAME NOT LIKE E.LAST_NAME;

--TASK 2
SELECT
    EMPLOYEE_ID,
    LAST_NAME,
    SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT
    EMPLOYEE_ID,
    LAST_NAME,
    SALARY
FROM EMPLOYEES
GROUP BY EMPLOYEE_ID,LAST_NAME, SALARY
HAVING SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);


-- TASK 3
SELECT
    E.EMPLOYEE_ID,
    E.LAST_NAME
FROM EMPLOYEES E JOIN EMPLOYEES D
ON E.DEPARTMENT_ID =  D.DEPARTMENT_ID
WHERE D.LAST_NAME LIKE '%u%';


--TASK 4
SELECT 
    E.LAST_NAME,
    E.DEPARTMENT_ID,
    E.JOB_ID
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.LOCATION_ID = 1700;

-- TASK 5
SELECT
    E.LAST_NAME,
    E.SALARY
FROM EMPLOYEES E JOIN EMPLOYEES K
ON E.MANAGER_ID = K.EMPLOYEE_ID 
AND K.LAST_NAME LIKE 'King';

-- TASK 6
SELECT
    DEPARTMENT_ID,
    LAST_NAME,
    JOB_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;


-- TASK 7
SELECT
    LAST_NAME
FROM EMPLOYEES
WHERE SALARY > (SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 60);


-- TASK 8
SELECT
    E.EMPLOYEE_ID,
    E.LAST_NAME
FROM EMPLOYEES E JOIN EMPLOYEES D
ON E.DEPARTMENT_ID =  D.DEPARTMENT_ID
WHERE D.LAST_NAME LIKE '%u%'
AND E.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);
